repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort

- repo: https://github.com/python/black
  rev: master
  hooks:
  - id: black
