language: python
cache:
  pip: true
  directories:
  - "$HOME/.cache/pypoetry"

stages:
    - linting
    - test
    - documentation
    - name: deploy
      if: branch = master

install:
    - pip install poetry tox

script:
    - tox -q -e $TASK

jobs:
    include:
        - python: 3.6
          env: TASK=py36

          after_success:
              - pip install coveralls
              - coveralls

        - python: 3.7
          dist: xenial
          env: TASK=py37

        - stage: linting
          python: 3.6
          env: TASK=lint


        - stage: documentation
          python: 3.6
          env: TASK=docs


        - stage: deploy
          name: Publish to PyPi
          python: 3.6
          script:
              - poetry build
          deploy:
              provider: script
              skip_cleanup: true
              script:
                - poetry publish --username $PYPI_USER --password $PYPI_PASS
              on:
                  branch: master

notifications:
    webhooks:
        urls:
        - https://webhooks.gitter.im/e/4bfa4fbff35ebee0a9d2
