trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - blog/*

jobs:
- job: 'Blog'
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      cd blog
      npm ci
      npm run deploy
    displayName: 'Build & Deploy'
