trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - blog/*

jobs:
- job: 'Blog'
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      cd blog
      npm ci
      npm run build
    displayName: Build

  - script: |
      git checkout -b gh-pages
      git config --global user.name "Tecyln Bot"
      git config --global user.email "teclyn.bot@ci.com"

      git add .
      git commit -m 'Gatsby Build'
      git remote -v
    displayName: Deploy
