trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - blog/*

jobs:
- job: 'Blog'
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      cd blog
      npm ci
      npm run build
      cp -r public $(Build.ArtifactStagingDirectory)
    displayName: Build

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'arlunio-blog'
