name: arlunio
version: 0.0.1
base: core18
grade: devel
summary: arlunio
description: |
  Arlunio allows you to create images and animations using a blend of Python
  and Mathematics
confinement: devmode
parts:
  arlunio:
    plugin: python
    python-version: python3
    python-packages:
    - arlunio[all]
apps:
  arlunio:
    command: bin/arlunio

